### PR TITLE
Bring `bazel generate` up-to-date with `make bazel-generate` at HEAD

### PR DESCRIPTION
**Pull request by rickystewart**

### CODE REVIEW

**Review by irfansharif — COMMENTED** [review]
Personally I think it's better to duplicate those 3 lines in-line here, as this diff ends up coupling the crdb SHA and the one here. It becomes difficult to amend that script/location once `dev` is stable, as it could behave differently depending on which crdb SHA is currently checked out.

(It's also more of a ["go-ism"](https://www.youtube.com/watch?v=PAAkCSZUG1c&t=9m28s))

**Comment by rickystewart** [comment]
Mm, well, I don't agree with that advice but I guess that's not the first time Rob Pike and I disagreed on something :p 

Now `generate bazel` is failing though, and the error looks like this:

```
cockroach$ ../dev/dev generate bazel
executing: /usr/local/bin/bazel run //:gazelle -- update-repos -from_file=go.mod -build_file_proto_mode=disable_global -to_macro=DEPS.bzl%go_deps -prune=true
INFO: Build option --run_under has changed, discarding analysis cache.
INFO: Analyzed target //:gazelle (0 packages loaded, 7195 targets configured).
INFO: Found 1 target...
Target //:gazelle up-to-date:
  bazel-bin/gazelle-runner.bash
  bazel-bin/gazelle
INFO: Elapsed time: 0.549s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
executing: /usr/local/bin/bazel run //:gazelle
INFO: Analyzed target //:gazelle (3 packages loaded, 106 targets configured).
INFO: Found 1 target...
Target //:gazelle up-to-date:
  bazel-bin/gazelle-runner.bash
  bazel-bin/gazelle
INFO: Elapsed time: 2.043s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
exit status 127
```

The error message is incredibly uninformative so I don't know what this means. Any ideas?

**Comment by irfansharif** [comment]
```go
	command := exec.Command("bazel", "run", "//pkg/cmd/generate-test-suites", fmt.Sprintf("--run_under='cd %s && '", cwd))
	command.Stderr = os.Stderr
	command.Stdout = os.Stdout
	if err := command.Run(); err != nil {
		return err
	}
	return nil
	// TODO: Capture output + write to pkg/BUILD.bazel.
```

```
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: /bin/bash -c ''\''cd /Users/irfansharif/Software/src/github.com/cockroachdb/cockroach && '\'' bazel-bin/pkg/cmd/generate-test-suites/generate-
INFO: Build completed successfully, 1 total action
/bin/bash: cd /Users/irfansharif/Software/src/github.com/cockroachdb/cockroach && : No such file or directory
exit status 127
```

I tried capturing the stdout/err for the raw exec command, and I think the `cd $PWD` bit is the problematic bit (though I'm unsure how).

**Comment by irfansharif** [comment]
Oh I think it's a string escape issue (`/bin/bash -c ''\''cd /Users/irfansharif/`). Try:
```go
	buf, err := exec.Command("bazel", "run", "//pkg/cmd/generate-test-suites", "--run_under", fmt.Sprintf("cd %s &&", cwd)).Output()
	if err != nil {
		return err
	}
	return ioutil.WriteFile(path.Join(cwd, "pkg/BUILD.bazel"), buf, 0644)

```

**Review by irfansharif — APPROVED** [review]

**Comment by irfansharif** [comment]
(we could also carry over the re-ordering from https://github.com/cockroachdb/cockroach/pull/60939)

**Comment by rickystewart** [comment]
That works, thanks for your help!!

**Pull request merged**
